[phases.setup]
nixPkgs = ["nodejs"]

[phases.build]
cmds = [
  "cd frontend",
  "npm install",
  "npm run build || echo 'No build script found, skipping'",
  "cd ../backend",
  "npm install"
]

[phases.start]
cmd = "node backend/server.js"
